AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scrobbify backend.

Resources:
  LoginEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.Handle
      Runtime: python2.7
      CodeUri: ./handler.zip
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /login
            Method: get
      Environment:
        Variables:
          SPOTIFY_ID: setme
          SPOTIFY_SECRET: setme
  SpotifyCallbackEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.Handle
      Runtime: python2.7
      CodeUri: ./handler.zip
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /spotifycallback
            Method: get
      Environment:
        Variables:
          SPOTIFY_ID: setme
          SPOTIFY_SECRET: setme
